# Generated by Django 5.2.6 on 2025-09-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(null=True, upload_to="post"),
        ),
    ]
